create table public.document_term_templates (
  id bigint generated by default as identity primary key,
  template_code text not null,
  template_name text not null,
  document_type text not null,
  version integer not null default 1,
  is_default boolean not null default false,
  status text not null default 'active',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint document_term_templates_code_check check (template_code ~ '^[A-Z][A-Z0-9-]{1,19}$'),
  constraint document_term_templates_name_check check (char_length(btrim(template_name)) between 1 and 120),
  constraint document_term_templates_document_type_check check (document_type in ('po', 'quotation', 'invoice')),
  constraint document_term_templates_version_check check (version > 0),
  constraint document_term_templates_status_check check (status in ('active', 'inactive')),
  constraint document_term_templates_code_unique unique (template_code)
);

create unique index document_term_templates_one_default_per_type_idx
  on public.document_term_templates(document_type)
  where is_default and status = 'active';

create table public.document_term_items (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.document_term_templates(id) on delete cascade,
  sort_order smallint not null,
  term_text text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint document_term_items_sort_order_check check (sort_order between 1 and 10),
  constraint document_term_items_text_check check (char_length(btrim(term_text)) between 1 and 500),
  constraint document_term_items_template_order_unique unique (template_id, sort_order)
);

create index document_term_items_template_idx on public.document_term_items(template_id, sort_order);

create trigger document_term_templates_set_updated_at
before update on public.document_term_templates
for each row execute function public.set_updated_at();

create trigger document_term_items_set_updated_at
before update on public.document_term_items
for each row execute function public.set_updated_at();

alter table public.document_term_templates enable row level security;
alter table public.document_term_items enable row level security;

create policy "Authenticated users can read document term templates"
on public.document_term_templates for select to authenticated using (true);
create policy "Owners can insert document term templates"
on public.document_term_templates for insert to authenticated
with check ((select public.is_current_user_owner()));
create policy "Owners can update document term templates"
on public.document_term_templates for update to authenticated
using ((select public.is_current_user_owner()))
with check ((select public.is_current_user_owner()));
create policy "Owners can delete document term templates"
on public.document_term_templates for delete to authenticated
using ((select public.is_current_user_owner()));

create policy "Authenticated users can read document term items"
on public.document_term_items for select to authenticated using (true);
create policy "Owners can insert document term items"
on public.document_term_items for insert to authenticated
with check ((select public.is_current_user_owner()));
create policy "Owners can update document term items"
on public.document_term_items for update to authenticated
using ((select public.is_current_user_owner()))
with check ((select public.is_current_user_owner()));
create policy "Owners can delete document term items"
on public.document_term_items for delete to authenticated
using ((select public.is_current_user_owner()));

grant select, insert, update, delete on public.document_term_templates to authenticated;
grant select, insert, update, delete on public.document_term_items to authenticated;
grant usage, select on sequence public.document_term_templates_id_seq to authenticated;
grant usage, select on sequence public.document_term_items_id_seq to authenticated;

insert into public.document_term_templates (
  template_code, template_name, document_type, is_default, status
) values (
  'PO-STD', 'เงื่อนไขการสั่งซื้อมาตรฐาน', 'po', true, 'active'
);

insert into public.document_term_items (template_id, sort_order, term_text)
select template.id, item.sort_order, item.term_text
from public.document_term_templates template
cross join (values
  (1, 'สินค้าต้องได้มาตรฐานตามที่บริษัทกำหนด'),
  (2, 'หากสินค้ามีตำหนิหรือไม่ได้คุณสมบัติ บริษัทขอสงวนสิทธิ์ในการคืนสินค้า')
) as item(sort_order, term_text)
where template.template_code = 'PO-STD';
