create table if not exists public.item_types (
  id bigint generated by default as identity primary key,
  type_code text not null,
  type_name text not null,
  type_name_en text,
  form_template text not null default 'general'
    check (form_template in ('general', 'raw_material', 'finished_good', 'asset', 'service')),
  code_mode text not null default 'auto' check (code_mode in ('auto', 'manual')),
  code_prefix text,
  is_stocked boolean not null default true,
  is_purchasable boolean not null default true,
  is_sellable boolean not null default false,
  is_production_item boolean not null default false,
  lot_controlled boolean not null default false,
  serial_controlled boolean not null default false,
  expiry_controlled boolean not null default false,
  dimension_enabled boolean not null default false,
  reorder_enabled boolean not null default false,
  status text not null default 'active' check (status in ('active', 'inactive')),
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint item_types_code_key unique (type_code),
  constraint item_types_name_key unique (type_name),
  constraint item_types_tracking_check check (not (lot_controlled and serial_controlled)),
  constraint item_types_prefix_check check (code_mode = 'manual' or nullif(btrim(code_prefix), '') is not null)
);

create table if not exists public.item_type_counters (
  item_type_id bigint primary key references public.item_types(id) on delete cascade,
  last_value bigint not null default 0 check (last_value >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.item_master (
  id bigint generated by default as identity primary key,
  item_type_id bigint not null references public.item_types(id),
  item_code text not null,
  item_name text not null,
  item_name_en text,
  description text,
  unit_id bigint references public.raw_material_units(id),
  tracking_method text not null default 'none' check (tracking_method in ('none', 'lot', 'serial')),
  shelf_life_days integer check (shelf_life_days is null or shelf_life_days > 0),
  reorder_point numeric(18, 4) check (reorder_point is null or reorder_point >= 0),
  attributes jsonb not null default '{}'::jsonb check (jsonb_typeof(attributes) = 'object'),
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint item_master_code_key unique (item_code)
);

create index if not exists item_types_status_sort_idx on public.item_types(status, sort_order, id);
create index if not exists item_master_type_status_idx on public.item_master(item_type_id, status, id);
create index if not exists item_master_name_idx on public.item_master(item_name);

insert into public.item_types (
  type_code, type_name, type_name_en, form_template, code_mode, code_prefix,
  is_stocked, is_purchasable, is_sellable, is_production_item,
  lot_controlled, serial_controlled, expiry_controlled, dimension_enabled,
  reorder_enabled, sort_order
)
values
  ('RM', 'วัตถุดิบ', 'Raw Material', 'raw_material', 'auto', 'RM', true, true, false, true, true, false, false, true, true, 10),
  ('WIP', 'งานระหว่างผลิต', 'Work in Process', 'general', 'auto', 'WIP', true, false, false, true, true, false, false, false, false, 20),
  ('FG', 'สินค้าสำเร็จรูป', 'Finished Good', 'finished_good', 'manual', null, true, false, true, true, false, false, false, false, false, 30),
  ('MRO', 'อะไหล่และของใช้', 'Maintenance, Repair and Operations', 'general', 'auto', 'MRO', true, true, false, false, false, false, false, false, true, 40),
  ('ASSET', 'ครุภัณฑ์', 'Fixed Asset', 'asset', 'auto', 'AST', false, true, false, false, false, true, false, false, false, 50),
  ('SERVICE', 'บริการ', 'Service', 'service', 'auto', 'SVC', false, true, true, false, false, false, false, false, false, 60),
  ('PACK', 'บรรจุภัณฑ์', 'Packaging Material', 'general', 'auto', 'PACK', true, true, false, true, true, false, false, true, true, 70)
on conflict (type_code) do nothing;

create or replace function public.reserve_item_code(p_item_type_id bigint)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_prefix text;
  v_mode text;
  v_value bigint;
begin
  if not public.authorize('mdm.create') then
    raise exception 'permission_denied' using errcode = '42501';
  end if;

  select code_mode, code_prefix into v_mode, v_prefix
  from public.item_types
  where id = p_item_type_id and status = 'active';

  if not found or v_mode <> 'auto' then
    raise exception 'item_type_not_auto_numbered';
  end if;

  insert into public.item_type_counters(item_type_id, last_value)
  values (p_item_type_id, 1)
  on conflict (item_type_id) do update
    set last_value = public.item_type_counters.last_value + 1,
        updated_at = now()
  returning last_value into v_value;

  return upper(v_prefix) || lpad(v_value::text, 4, '0');
end;
$$;

alter table public.item_types enable row level security;
alter table public.item_type_counters enable row level security;
alter table public.item_master enable row level security;

create policy item_types_select on public.item_types for select to authenticated using (public.authorize('mdm.view'));
create policy item_types_insert on public.item_types for insert to authenticated with check (public.authorize('mdm.create'));
create policy item_types_update on public.item_types for update to authenticated using (public.authorize('mdm.edit')) with check (public.authorize('mdm.edit'));
create policy item_types_delete on public.item_types for delete to authenticated using (public.authorize('mdm.delete'));
create policy item_master_select on public.item_master for select to authenticated using (public.authorize('mdm.view'));
create policy item_master_insert on public.item_master for insert to authenticated with check (public.authorize('mdm.create'));
create policy item_master_update on public.item_master for update to authenticated using (public.authorize('mdm.edit')) with check (public.authorize('mdm.edit'));
create policy item_master_delete on public.item_master for delete to authenticated using (public.authorize('mdm.delete'));

revoke all on public.item_types, public.item_type_counters, public.item_master from anon;
grant select, insert, update, delete on public.item_types, public.item_master to authenticated;
grant usage, select on sequence public.item_types_id_seq, public.item_master_id_seq to authenticated;
grant execute on function public.reserve_item_code(bigint) to authenticated;
